<a href="https://colab.research.google.com/github/xx529/Reinforcement-Learning/blob/main/Policy%20Gradient/Reducing_Variance_Using_Baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reducing_Variance_Using_Baseline

* $\nabla E_{\tau\sim\pi_{\theta}}[R]=E_{\tau}[\sum_{t=0}^{\tau-1}G_t \nabla_{\theta}log\pi_{\theta}(a_t|s_t)]$

* 其中 $G_t=\sum_{t^{\prime}=t}^{\tau-1}r_{t^{\prime}}$ 就是在 $t^{\prime}$ 时刻的总 reward 

# Agent

In [35]:
import torch.nn as nn
import torch

class Agent(nn.Module):
    def __init__(self, ):
        super(Agent, self).__init__()
        self.fc1 = nn.Linear(4, 128)
        self.fc2 = nn.Linear(128, 2)
        self.dropout = nn.Dropout(p=0.6)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)

        # self.current_policy = 
        

    def forward(self, x):
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc2(x)
        policy = self.softmax(x)
        return policy

# Emulator

In [95]:
import gym
from torch.distributions import Categorical

class Emulator:
    def __init__(self, name, gamma=0.9):
        self.env = gym.make(name)
        self.gamma = gamma
        self.current_state = None
        self.reward_seq = []

    def step(self, agent):
        action_probs = agent(torch.from_numpy(self.current_state).float().unsqueeze(0))
        action = Categorical(action_probs).sample().item()
        self.current_state, reward, done, _ = self.env.step(action)
        self.reward_seq.append(reward)


        
        return self.current_state

    def reset(self):
        self.current_state = self.env.reset()
        self.reward_seq = []

    def get_Gt(self):
        for i in self.reward_seq[::-1]:
            

In [96]:
agent = Agent()
emulator = Emulator('CartPole-v1')


emulator.reset()
emulator.step(agent)
emulator.step(agent)

array([-0.03397693, -0.02535876,  0.0074242 ,  0.03120025])

In [97]:
emulator.reward_list

[1.0, 1.0]

In [13]:
env.step(0)

/usr/local/lib/python3.7/dist-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


(array([-0.08764318, -1.71546854,  0.27073459,  2.93805168]), 0.0, True, {})

In [55]:
env = gym.make('CartPole-v1')

In [56]:
env.reset()

array([-0.02754705, -0.00197631, -0.00116885, -0.02404558])

In [58]:
env.step(0)

(array([-0.02758658, -0.19708147, -0.00164976,  0.26826833]), 1.0, False, {})